# Generated by Django 4.1 on 2022-08-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(to='library_catalogue.book'),
        ),
        migrations.DeleteModel(
            name='BookAuthorLink',
        ),
    ]
